[package]
name = "homesec"
version = "0.1.0"
authors = ["Seth Moeckel <seth.moeckel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.46.3"
dlib-face-recognition = "0.1.7"